package com.zipzaptaxi.live.model

data class GetWalletModel(
    val code: Int,
    val data: Data,
    val message: String,
    val success: Boolean
) {
    data class Data(
        val balance: String,
        val bookings: ArrayList<Booking>,
        val collect_amount: String,
        val note_balance: String,
        val paid: String,
        val panelty: String,
        val referal_amount: String,
        val vendor_amount: String
    ) {
        data class Booking(
            val booking_id: Int,
            val booking_unique_id: String,
            val car_type: String,
            val trip: String,
            val distance: String,
            val time_to_cover: String,
            val source: String,
            val stops: Map<String, String>,
            val destination: String,
            val passengers: String,
            val bags: String,
            val name: String,
            val email: String,
            val mobile: String,
            val alternate_no: String,
            val pickLoc: String,
            val dropLoc: String,
            val gst_no: String,
            val ride_date: String,
            val ride_time: String,
            val ride_end_date: String,
            val ride_end_time: String,
            val roofTop: String,
            val roof_charges: String,
            val pickup_charges: String,
            val drop_charges: String,
            val night_charges: String,
            val other_comments: String,
            val price: String,
            val vendor_amount: String,
            val balance: String,
            val penalty: Int,
            val extra_charge: String,
            val extra_time_charge: String,
            val toll_tax: String,
            val state_tax: String,
            val driver_allowance: String,
            val airport_charge: String,
            val parking: String,
            val night_pick: String,
            val night_drop: String,
            val cab_model: String,
            val cab_image: String,
            val booking_status: String,
            val status: String,
            val assigned_to_me: Int,
            val assigned_to_other: Int,
            val get_otp: Int,
            val assigned_driver: Any, // Nullable type for missing driver data
            val assigned_cab: Int,
            val extra_km_driven: Int,
            val extra_km_price: Int,
            val extra_min: Int,
            val extra_min_price: Int,
            val total_price_with_extra_km: Int,
            val cancellation_time: String
        )
    }
}
